In [184]:
from transformers import AutoTokenizer, AutoModel
import numpy as np
import torch

In [185]:
#sent1 = 'New York is the city where I like.'
#sent1 = 'New York is the economic center of the world.'
#sent1 = 'New York is a poor city.'
sent1 = 'I like living in New York.'
#sent2 = 'New York is a prosperous city.'
sent2 = 'I like living in New York.'


In [186]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
model = AutoModel.from_pretrained('bert-base-cased', output_hidden_states=True).eval()

c:\Users\guoya\anaconda3\lib\site-packages\huggingface_hub-0.23.0-py3.8.egg\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [187]:
tok1 = tokenizer(sent1, return_tensors='pt')
tok2 = tokenizer(sent2, return_tensors='pt')

In [188]:
# This is where the "New" and "York" can be found in sent1
sent1_idxs = [4, 5]
#sent1_idxs = [0, 1]
#sent2_idxs = [0, 1]
sent2_idxs = [4, 5]

tok1_ids = [np.where(np.array(tok1.word_ids()) == idx) for idx in sent1_idxs]
tok2_ids = [np.where(np.array(tok2.word_ids()) == idx) for idx in sent2_idxs]

In [189]:
with torch.no_grad():
    out1 = model(**tok1)
    out2 = model(**tok2)

# Only grab the last hidden state
states1 = out1.hidden_states[-1].squeeze()
states2 = out2.hidden_states[-1].squeeze()

# Select the tokens that we're after corresponding to "New" and "York"
embs1 = states1[[tup[0][0] for tup in tok1_ids]]
embs2 = states2[[tup[0][0] for tup in tok2_ids]]

In [190]:
avg1 = embs1.mean(axis=0)
avg2 = embs2.mean(axis=0)

In [191]:
torch.cosine_similarity(avg1.reshape(1,-1), avg2.reshape(1,-1))

tensor([1.])

In [192]:
sent3 = 'I like eating apple the fruit.'

#sent4 = 'I like using apple the computer.'
sent4 ="I like using apple phone"

In [193]:
tok3 = tokenizer(sent3, return_tensors='pt')
tok4 = tokenizer(sent4, return_tensors='pt')

In [194]:
# This is where the "New" and "York" can be found in sent1
#sent1_idxs = [4, 5]
sent3_idxs = [3]
sent4_idxs = [4]
#sent2_idxs = [4, 5]

tok3_ids = [np.where(np.array(tok1.word_ids()) == idx) for idx in sent3_idxs]
tok4_ids = [np.where(np.array(tok2.word_ids()) == idx) for idx in sent4_idxs]

print(tok3_ids[0][0])

[4]


In [195]:
with torch.no_grad():
    out3 = model(**tok3)
    out4 = model(**tok4)

# Only grab the last hidden state
states3 = out3.hidden_states[-1].squeeze()
states4 = out4.hidden_states[-1].squeeze()

# Select the tokens that we're after corresponding to "New" and "York"
embs3 = states3[[tup[0][0] for tup in tok3_ids]]
embs4 = states4[[tup[0][0] for tup in tok4_ids]]

In [196]:
torch.cosine_similarity(embs3.reshape(1,-1), embs4.reshape(1,-1))

tensor([0.6500])

In [197]:
tokenizer_c = AutoTokenizer.from_pretrained('bert-base-chinese')
model_c = AutoModel.from_pretrained('bert-base-chinese', output_hidden_states=True).eval()

In [219]:
sent5 = '我喜欢吃苹果.'

#sent4 = 'I like using apple the computer.'
#sent6 ="我喜欢用苹果手机"
#sent6 ="我喜欢用华为手机"
sent6 = '我不喜欢吃苹果.'
#sent6 = '我喜欢吃芒果.'


In [220]:
tok5 = tokenizer_c(sent5, return_tensors='pt')
tok6 = tokenizer_c(sent6, return_tensors='pt')

In [221]:

sent5_idxs = [4,5]
sent6_idxs = [5,6]

tok5_ids = [np.where(np.array(tok5.word_ids()) == idx) for idx in sent5_idxs]
tok6_ids = [np.where(np.array(tok6.word_ids()) == idx) for idx in sent6_idxs]

print(tok5_ids[0][0])

[5]


In [222]:
with torch.no_grad():
    out5 = model_c(**tok5)
    out6 = model_c(**tok6)

# Only grab the last hidden state
states5 = out5.hidden_states[-1].squeeze()
states6 = out6.hidden_states[-1].squeeze()

# Select the tokens that we're after corresponding to "New" and "York"
embs5 = states5[[tup[0][0] for tup in tok5_ids]]
embs6 = states6[[tup[0][0] for tup in tok6_ids]]

In [223]:
avg5 = embs5.mean(axis=0)
avg6 = embs6.mean(axis=0)
print(avg5,avg6)

tensor([ 1.0451e+00, -8.2742e-01, -8.5824e-01, -7.2667e-01,  5.0866e-01,
        -4.9863e-01,  6.4319e-02,  6.9619e-01,  4.2772e-02,  6.4843e-01,
        -1.5347e-01, -8.2764e-01,  2.3303e-02, -1.2481e-01,  6.6088e-01,
         1.1456e-01,  2.6875e-01, -5.0612e-01,  7.1723e-01,  5.3462e-01,
        -6.1121e-01,  1.0106e+00,  7.8630e-01, -2.9076e-01,  1.9336e-01,
        -1.7458e-01,  4.7783e-01, -9.8522e-01, -2.4357e-01, -3.5911e-01,
         4.9839e-01, -1.4781e-01, -7.0075e-01, -4.4000e-01, -5.1512e-01,
         2.2881e-01, -1.2832e-01,  3.2581e-01, -6.7071e-02, -2.1910e-01,
         5.3251e-01, -7.2977e-01,  3.6588e-01,  3.4491e-01, -2.3614e-01,
        -3.4344e-01, -6.3558e-01, -1.2779e-01,  1.0109e-01,  2.1607e-01,
         2.0620e-01,  9.2411e+00,  1.7513e-01,  3.3441e-01, -1.1986e-02,
        -4.2553e-01,  1.3208e+00, -2.5003e-01, -1.0535e-01, -6.4096e-01,
         6.7449e-01, -9.2742e-01, -1.9602e-01,  2.4840e-01, -1.6261e-01,
        -3.7969e-01,  4.3926e-01, -3.9066e-01, -2.2

In [224]:
torch.cosine_similarity(avg5.reshape(1,-1), avg6.reshape(1,-1))

tensor([0.9173])

In [225]:
#!pip install allennlp